In [1]:
import yfinance as yf
import pandas as pd

In [24]:
t50_tickers = [
    "2222.SR", "1120.SR", "1211.SR", "1180.SR", "7010.SR", "2010.SR", "2082.SR", "1010.SR", "4013.SR", "1150.SR",
    "1060.SR", "5110.SR", "2020.SR", "7203.SR", "7020.SR", "1050.SR", "1080.SR", "2280.SR", "4280.SR", "1140.SR",
    "4030.SR", "2380.SR", "7202.SR", "8210.SR", "4325.SR", "2382.SR", "8010.SR", "2223.SR", "2290.SR", "4300.SR",
    "1303.SR", "4190.SR", "4142.SR", "4250.SR", "1030.SR", "6015.SR", "1111.SR", "4100.SR", "1020.SR", "4002.SR",
    "4164.SR", "4263.SR", "4004.SR", "4200.SR", "2310.SR", "8313.SR", "1212.SR", "4015.SR", "8230.SR", "4220.SR"
]

In [154]:
top_50 = yf.download(t50_tickers, start="2023-1-1" , end="2026-5-9")

[*********************100%***********************]  50 of 50 completed

In [155]:
top_50.shape

(835, 250)

In [156]:
top_50.head()

Price           Close                                                         \
Ticker        1010.SR    1020.SR    1030.SR    1050.SR    1060.SR    1080.SR
Date
2023-01-01  19.938663  11.810729  11.832534  16.675842  32.377926  19.850248
2023-01-02  19.812864  11.810729  11.859798  16.430609  32.419487  20.096838
2023-01-03  19.812864  11.810729  11.859798  16.430609  32.419487  20.096838
2023-01-04  19.498377  11.736988  11.846167  16.451040  32.336361  19.480368
2023-01-05  19.309679  11.810729  12.268757  16.471479  32.627304  19.726954

Price                                                    ...    Volume  \
Ticker         1111.SR    1120.SR    1140.SR    1150.SR  ...   5110.SR
Date                                                     ...
2023-01-01  173.061066  45.546246  27.215340  19.242661  ...  233513.0
2023-01-02  173.627853  45.968536  27.091776  19.360714  ...  319496.0
2023-01-03  173.627853  45.968536  27.091776  19.360714  ...       0.0
2023-01-04  170.227097  45.968536  27.122665  19.242661  ...  707763.0
2023-01-05  168.148849  45.666904  27.184448  19.242661  ...  825490.0

Price                                                                  \
Ticker        6015.SR  7010.SR   7020.SR   7202.SR  7203.SR   8010.SR
Date
2023-01-01   10307561  1267439  258070.0   20765.0  18707.0   51126.0
2023-01-02   44242467  1690505  336578.0   69039.0  56607.0  200371.0
2023-01-03          0  1620673       0.0       0.0      0.0       0.0
2023-01-04  112373599  2619715  904120.0   96029.0  74785.0  173101.0
2023-01-05   72216095  2268620  701895.0  100657.0  83953.0  154608.0

Price
Ticker      8210.SR   8230.SR 8313.SR
Date
2023-01-01  18769.0  148075.0     NaN
2023-01-02  24830.0  138342.0     NaN
2023-01-03      0.0       0.0     NaN
2023-01-04  52123.0  376875.0     NaN
2023-01-05  46870.0  195790.0     NaN

[5 rows x 250 columns]

In [157]:
top_50 = top_50.dropna(how="all", subset=[('Close',t) for t in top_50.Close.columns])

In [158]:
top_50.shape

(835, 250)

In [159]:
top_50.isna().sum()

Price   Ticker
Close   1010.SR      0
        1020.SR      0
        1030.SR      0
        1050.SR      0
        1060.SR      1
                  ...
Volume  7203.SR      1
        8010.SR      1
        8210.SR      1
        8230.SR      1
        8313.SR    362
Length: 250, dtype: int64

In [160]:
top_50.Close.isna().sum()

Ticker
1010.SR      0
1020.SR      0
1030.SR      0
1050.SR      0
1060.SR      1
1080.SR      0
1111.SR      1
1120.SR      0
1140.SR      0
1150.SR      0
1180.SR      1
1211.SR      1
1212.SR      1
1303.SR      1
2010.SR      1
2020.SR      1
2082.SR      0
2222.SR      0
2223.SR      1
2280.SR      1
2290.SR      1
2310.SR      1
2380.SR      1
2382.SR    194
4002.SR      1
4004.SR      1
4013.SR      1
4015.SR    129
4030.SR      0
4100.SR      0
4142.SR      1
4164.SR      1
4190.SR      1
4200.SR      0
4220.SR      0
4250.SR      1
4263.SR    209
4280.SR      1
4300.SR      1
4325.SR    556
5110.SR      1
6015.SR      0
7010.SR      0
7020.SR      1
7202.SR      1
7203.SR      1
8010.SR      1
8210.SR      1
8230.SR      1
8313.SR    362
dtype: int64

In [161]:
top_50

Price           Close                                                         \
Ticker        1010.SR    1020.SR    1030.SR    1050.SR    1060.SR    1080.SR
Date
2023-01-01  19.938663  11.810729  11.832534  16.675842  32.377926  19.850248
2023-01-02  19.812864  11.810729  11.859798  16.430609  32.419487  20.096838
2023-01-03  19.812864  11.810729  11.859798  16.430609  32.419487  20.096838
2023-01-04  19.498377  11.736988  11.846167  16.451040  32.336361  19.480368
2023-01-05  19.309679  11.810729  12.268757  16.471479  32.627304  19.726954
...               ...        ...        ...        ...        ...        ...
2026-05-03  20.770000  11.830000  13.450000  19.080000  34.000000  21.660000
2026-05-04  20.770000  11.830000  13.450000  19.080000  34.000000  21.660000
2026-05-05  20.900000  11.620000  13.180000  19.100000  33.939999  21.150000
2026-05-06  20.850000  11.560000  13.180000  19.180000  33.759998  21.049999
2026-05-07  20.840000  11.550000  13.400000  19.400000  34.180000  21.070000

Price                                                    ...     Volume  \
Ticker         1111.SR    1120.SR    1140.SR    1150.SR  ...    5110.SR
Date                                                     ...
2023-01-01  173.061066  45.546246  27.215340  19.242661  ...   233513.0
2023-01-02  173.627853  45.968536  27.091776  19.360714  ...   319496.0
2023-01-03  173.627853  45.968536  27.091776  19.360714  ...        0.0
2023-01-04  170.227097  45.968536  27.122665  19.242661  ...   707763.0
2023-01-05  168.148849  45.666904  27.184448  19.242661  ...   825490.0
...                ...        ...        ...        ...  ...        ...
2026-05-03  134.600006  68.750000  24.566698  24.132830  ...  2058495.0
2026-05-04  134.600006  68.750000  24.566698  24.132830  ...        0.0
2026-05-05  133.500000  66.949997  24.420000  23.469894  ...  2131483.0
2026-05-06  136.500000  66.500000  24.570000  23.459999  ...  4170682.0
2026-05-07  136.800003  66.599998  24.520000  23.530001  ...  1806918.0

Price                                                                    \
Ticker        6015.SR  7010.SR   7020.SR   7202.SR   7203.SR    8010.SR
Date
2023-01-01   10307561  1267439  258070.0   20765.0   18707.0    51126.0
2023-01-02   44242467  1690505  336578.0   69039.0   56607.0   200371.0
2023-01-03          0  1620673       0.0       0.0       0.0        0.0
2023-01-04  112373599  2619715  904120.0   96029.0   74785.0   173101.0
2023-01-05   72216095  2268620  701895.0  100657.0   83953.0   154608.0
...               ...      ...       ...       ...       ...        ...
2026-05-03   20025235  2664728  139490.0   87203.0  194405.0    90057.0
2026-05-04          0        0       0.0       0.0       0.0        0.0
2026-05-05   43600494  1884686  350316.0   91394.0  157844.0   142053.0
2026-05-06   29142688  2220345  983285.0   98706.0  232244.0  1540841.0
2026-05-07   31915176  2877294  634721.0  338655.0  210512.0   563026.0

Price
Ticker       8210.SR   8230.SR    8313.SR
Date
2023-01-01   18769.0  148075.0        NaN
2023-01-02   24830.0  138342.0        NaN
2023-01-03       0.0       0.0        NaN
2023-01-04   52123.0  376875.0        NaN
2023-01-05   46870.0  195790.0        NaN
...              ...       ...        ...
2026-05-03   54886.0  124624.0   184508.0
2026-05-04       0.0       0.0  1296579.0
2026-05-05  191089.0  559992.0   884628.0
2026-05-06  185146.0  276898.0   375438.0
2026-05-07  160534.0  147917.0   269041.0

[835 rows x 250 columns]

In [266]:
df_long = top_50.stack(level=1).reset_index()

In [267]:
df_long.columns.name = None

In [268]:
null_summary = df_long.isna().groupby(df_long['Close']).sum()

In [269]:
before= len(df_long)

In [270]:
df_long = df_long.dropna(subset=["Close"])

In [271]:
after = len(df_long)

In [272]:
difference = before - after

In [273]:
difference

1479

In [274]:
df_long.tail()

,Date,Ticker,Close,High,Low,Open,Volume
41745,2026-05-07,7203.SR,657.500000,657.500000,657.500000,657.500000,210512.0
41746,2026-05-07,8010.SR,141.800003,142.000000,137.100006,137.100006,563026.0
41747,2026-05-07,8210.SR,180.100006,182.199997,179.199997,181.500000,160534.0
41748,2026-05-07,8230.SR,106.800003,108.599998,106.800003,108.199997,147917.0
41749,2026-05-07,8313.SR,145.300003,147.800003,144.600006,145.500000,269041.0

In [275]:
zeros = df_long[df_long.Volume == 0]

In [276]:
zeros

,Date,Ticker,Close,High,Low,Open,Volume
100,2023-01-03,1010.SR,19.812864,19.812864,19.812864,19.812864,0.0
101,2023-01-03,1020.SR,11.810729,11.810729,11.810729,11.810729,0.0
102,2023-01-03,1030.SR,11.859798,11.859798,11.859798,11.859798,0.0
103,2023-01-03,1050.SR,16.430609,16.430609,16.430609,16.430609,0.0
104,2023-01-03,1060.SR,32.419487,32.419487,32.419487,32.419487,0.0
...,...,...,...,...,...,...,...
41594,2026-05-04,7202.SR,223.199997,223.199997,223.199997,223.199997,0.0
41595,2026-05-04,7203.SR,616.000000,616.000000,616.000000,616.000000,0.0
41596,2026-05-04,8010.SR,131.000000,131.000000,131.000000,131.000000,0.0
41597,2026-05-04,8210.SR,180.000000,180.000000,180.000000,180.000000,0.0
41598,2026-05-04,8230.SR,111.599998,111.599998,111.599998,111.599998,0.0

In [296]:
before_zeros = len(df_long)
before_zeros

40271

In [280]:
zeros.info()

<class 'pandas.DataFrame'>
Index: 1728 entries, 100 to 41598
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1728 non-null   datetime64[s]
 1   Ticker  1728 non-null   str
 2   Close   1728 non-null   float64
 3   High    1728 non-null   float64
 4   Low     1728 non-null   float64
 5   Open    1728 non-null   float64
 6   Volume  1728 non-null   float64
dtypes: datetime64[s](1), float64(5), str(1)
memory usage: 120.0 KB

In [288]:
trial = df_long.dropna().loc[df_long.Volume > 0]

In [290]:
trial.shape

(38543, 7)

In [297]:
after_zeros = len(trial)
difference_zeros = before_zeros - after_zeros

In [298]:
difference_zeros

1728

In [299]:
after_zeros

38543

In [300]:
before_zeros

40271

In [303]:
leftovers = trial[trial.Volume == 0]

In [304]:
leftovers

Empty DataFrame
Columns: [Date, Ticker, Close, High, Low, Open, Volume]
Index: []

In [306]:
len(top_50)

835

In [309]:
df_long = trial

In [311]:
df_long.info()

<class 'pandas.DataFrame'>
Index: 38543 entries, 0 to 41749
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    38543 non-null  datetime64[s]
 1   Ticker  38543 non-null  str
 2   Close   38543 non-null  float64
 3   High    38543 non-null  float64
 4   Low     38543 non-null  float64
 5   Open    38543 non-null  float64
 6   Volume  38543 non-null  float64
dtypes: datetime64[s](1), float64(5), str(1)
memory usage: 2.6 MB

In [322]:
median_tickers = df_long.groupby("Ticker")["Volume"].median()

In [332]:
median_tickers.min()

np.float64(67862.5)

In [333]:
median_tickers.sort_values()

Ticker
4004.SR       67862.5
7203.SR       73468.0
4100.SR      100381.0
1212.SR      101700.0
4015.SR      103604.5
8210.SR      113016.0
7202.SR      115674.0
1111.SR      144543.0
4164.SR      146971.5
4013.SR      148686.0
8230.SR      166590.0
4263.SR      177147.0
4142.SR      204713.5
4280.SR      224938.0
2082.SR      242277.0
4200.SR      255243.0
8010.SR      257793.0
2223.SR      258861.0
4002.SR      305469.0
4220.SR      411421.0
2020.SR      442617.0
8313.SR      486109.0
2290.SR      491341.0
4030.SR      526927.0
1030.SR      568281.0
2280.SR      599825.0
7020.SR      803951.0
5110.SR     1088045.0
1080.SR     1260070.0
1060.SR     1292451.0
1140.SR     1307229.0
2010.SR     1365733.0
2310.SR     1367404.0
4190.SR     1448826.0
1050.SR     1488845.0
2380.SR     1514620.0
1211.SR     1637460.0
4325.SR     1748053.0
4300.SR     1864162.0
4250.SR     2133400.0
2382.SR     2249636.0
1010.SR     2312573.0
1020.SR     2900457.0
7010.SR     3002794.0
1180.SR     4145315.0
1303.SR     4172813.0
1120.SR     4875054.0
1150.SR     5359672.0
2222.SR    10398563.0
6015.SR    14624082.0
Name: Volume, dtype: float64

In [334]:
median_tickers.describe()

count    5.000000e+01
mean     1.621933e+06
std      2.629231e+06
min      6.786250e+04
25%      2.097696e+05
50%      5.840530e+05
75%      1.720405e+06
max      1.462408e+07
Name: Volume, dtype: float64

In [352]:
trial = df_long.dropna().loc[df_long.groupby("Ticker")["Volume"].transform("median") > 110000]

In [353]:
print(len(df_long) - len(trial))

3890

In [354]:
print(trial.groupby("Ticker")["Volume"].transform("median").min())

113016.0

In [355]:
trial.Ticker.count()

np.int64(34653)

In [356]:
trial.shape

(34653, 7)

In [357]:
trial.Ticker.nunique()

45

In [358]:
trial.shape[0]

34653

In [359]:
df_long = trial

In [360]:
df_long.shape

(34653, 7)

In [361]:
trial = df_long.groupby("Ticker").size()

In [362]:
trial

Ticker
1010.SR    798
1020.SR    796
1030.SR    796
1050.SR    769
1060.SR    795
1080.SR    795
1111.SR    794
1120.SR    798
1140.SR    796
1150.SR    798
1180.SR    795
1211.SR    797
1303.SR    796
2010.SR    797
2020.SR    797
2082.SR    795
2222.SR    809
2223.SR    797
2280.SR    795
2290.SR    797
2310.SR    797
2380.SR    797
2382.SR    641
4002.SR    796
4013.SR    797
4030.SR    799
4142.SR    794
4164.SR    796
4190.SR    795
4200.SR    797
4220.SR    794
4250.SR    796
4263.SR    626
4280.SR    795
4300.SR    796
4325.SR    279
5110.SR    795
6015.SR    795
7010.SR    811
7020.SR    795
7202.SR    795
8010.SR    795
8210.SR    796
8230.SR    795
8313.SR    471
dtype: int64

In [363]:
trial.describe()

count     45.000000
mean     770.066667
std       94.958460
min      279.000000
25%      795.000000
50%      796.000000
75%      797.000000
max      811.000000
dtype: float64

In [364]:
trial.head(100)

Ticker
1010.SR    798
1020.SR    796
1030.SR    796
1050.SR    769
1060.SR    795
1080.SR    795
1111.SR    794
1120.SR    798
1140.SR    796
1150.SR    798
1180.SR    795
1211.SR    797
1303.SR    796
2010.SR    797
2020.SR    797
2082.SR    795
2222.SR    809
2223.SR    797
2280.SR    795
2290.SR    797
2310.SR    797
2380.SR    797
2382.SR    641
4002.SR    796
4013.SR    797
4030.SR    799
4142.SR    794
4164.SR    796
4190.SR    795
4200.SR    797
4220.SR    794
4250.SR    796
4263.SR    626
4280.SR    795
4300.SR    796
4325.SR    279
5110.SR    795
6015.SR    795
7010.SR    811
7020.SR    795
7202.SR    795
8010.SR    795
8210.SR    796
8230.SR    795
8313.SR    471
dtype: int64

In [374]:
trial = df_long.dropna().loc[df_long.groupby("Ticker").transform("size") > 500]

In [375]:
trial.head()

        Date   Ticker      Close       High        Low       Open     Volume
0 2023-01-01  1010.SR  19.938663  20.158807  19.938663  20.064459   307379.0
1 2023-01-01  1020.SR  11.810729  11.859889  11.749279  11.749279  2260396.0
2 2023-01-01  1030.SR  11.832534  11.832534  11.750742  11.791639   141395.0
3 2023-01-01  1050.SR  16.675842  16.716714  16.451045  16.716714   165957.0
4 2023-01-01  1060.SR  32.377926  32.544180  32.128546  32.419489   188123.0

In [376]:
test = trial.groupby("Ticker").size()

In [377]:
test.min()

np.int64(626)

In [378]:
test

Ticker
1010.SR    798
1020.SR    796
1030.SR    796
1050.SR    769
1060.SR    795
1080.SR    795
1111.SR    794
1120.SR    798
1140.SR    796
1150.SR    798
1180.SR    795
1211.SR    797
1303.SR    796
2010.SR    797
2020.SR    797
2082.SR    795
2222.SR    809
2223.SR    797
2280.SR    795
2290.SR    797
2310.SR    797
2380.SR    797
2382.SR    641
4002.SR    796
4013.SR    797
4030.SR    799
4142.SR    794
4164.SR    796
4190.SR    795
4200.SR    797
4220.SR    794
4250.SR    796
4263.SR    626
4280.SR    795
4300.SR    796
5110.SR    795
6015.SR    795
7010.SR    811
7020.SR    795
7202.SR    795
8010.SR    795
8210.SR    796
8230.SR    795
dtype: int64

In [379]:
trial.shape

(33903, 7)

In [380]:
print(len(df_long) - len(trial))

750

In [381]:
trial.Ticker.nunique()

43

In [382]:
len(trial)

33903

In [383]:
df_long = trial

In [384]:
df_long.to_parquet("data/tadawul_clean.parquet")

OSError: Cannot save file into a non-existent directory: 'data'

In [389]:
import os

print(os.getcwd())

c:\Users\iizey\Documents\some_projects\saudi-stock-classifier\data

In [392]:
df_long.to_parquet("../data/tadawul_clean.parquet")